language: c++
compiler: gcc
sudo: true

branches:
  only:
  - master
  - ci/all
  - ci/travis
  - develop

matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

  # - os: linux
  #   dist: trusty
  #   sudo: required
  #   env: TARGET="linux"
  #   cache:
  #     directories:
  #       - ~/Dev
  #       - third_party
        
  #   addons:
  #     apt:
  #       sources:
  #         - ubuntu-toolchain-r-test
  #       packages:
  #         - gcc-4.9
  #         - g++-4.9
  #         - gdb


  # - os: linux
  #   sudo: required
  #   dist: trusty
  #   env: TARGET="linuxarmv6"


  # - os: linux
  #   sudo: false
  #   env: TARGET="linuxarmv7"
  #   cache:
  #     directories:
  #       - ~/rpi2_toolchain


  - os: osx
    osx_image: xcode8
    compiler: clang
    env: 
      - TARGET="osx"
      - CONFIGURATION="Release"
    cache:
      directories:
        - ~/Dev
        - third_party



  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

install:
  - if [ "$TARGET" == "linux" ]|| [ "$TARGET" == "linuxarmv6" ] || [ "$TARGET" == "linuxarmv7" ]; then
        sudo sh Scripts/linux/installDeps.sh && sudo  sh Scripts/linux/installDevDeps.sh;
    elif [ "$TARGET" == "osx" ] ; then
        sh Scripts/osx/installDevDeps.sh && sh Scripts/osx/installExportDeps.sh;
    fi


script:
    - python3 Scripts/buildScript.py --configure --build --configuration=$CONFIGURATION --os=$TARGET;

after_success:
  - python3 Scripts/buildScript.py --package --export;

git:
  depth: 100
