# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get install libfreetype6-dev
          - apt-get install libx11-dev
          - apt-get install libxinerama-dev
          - apt-get install libxrandr-dev
          - apt-get install libxcursor-dev
          - apt-get install mesa-common-dev
          - apt-get install libasound2-dev
          - apt-get install freeglut3-dev
          - apt-get install libxcomposite-dev
          - cd src/LGML/Builds/LinuxMakefile/
          - make
          