# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: tintamarajah/ubuntu16juce

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - uname -a && lscpu
          - mkdir ${HOME}/Dev && ln -s /JUCE ${HOME}/Dev/JUCE
          - cd src/LGML/Builds/LinuxMakefile/
          - make CONFIG=Ubuntu -j8
          - apt-get install -y --no-install-recommends tar curl
          - tar -zcvf LGML.tar.gz --directory="build/" LGML
          - LGMLversion=$(python ../../Scripts/PyUtils/ProJucerUtils.py)
          - curl -X PUT "${owncloudA}/remote.php/webdav/Tools/LGML/App-Dev/Linux/Ubuntu16.04/LGML64${LGMLversion}_bleedingEdge.tar.gz" --data-binary @"LGML.tar.gz" -u ${owncloudU}:${owncloudP} -k

          